name: iOS IPA Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Installer SVN
        run: |
          brew install subversion

      - name: Cloner le projet depuis SVN
        run: |
          echo "Téléchargement du code depuis SVN..."
          svn checkout --username "${{ secrets.SVN_USERNAME }}" --password "${{ secrets.SVN_PASSWORD }}" https://svn.jiscomputing.com/jcardsmobile/ project

      - name: Installer Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.1
          architecture: x64

      - name: Installer les dépendances Flutter
        run: |
          cd project
          flutter pub get

      - name: Corriger la version minimale iOS
        run: |
          cd project/ios
          sed -i '' 's/platform :ios, '9.0'/platform :ios, '12.0'/' Podfile
          pod install --repo-update

      - name: Désactiver la signature automatique dans Xcode
        run: |
            cd project/ios
            /usr/libexec/PlistBuddy -c "Set :ProvisioningStyle Manual" Runner.xcodeproj/project.pbxproj
            /usr/libexec/PlistBuddy -c "Set :CODE_SIGN_IDENTITY \"\"" Runner.xcodeproj/project.pbxproj
            /usr/libexec/PlistBuddy -c "Set :DEVELOPMENT_TEAM \"\"" Runner.xcodeproj/project.pbxproj

      - name: Compiler l’application iOS
        run: |
          cd project
          flutter build ios --release --no-codesign

      - name: Créer ExportOptions.plist
        run: |
            cat <<EOF > project/ios/ExportOptions.plist
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
              <key>method</key>
              <string>release-testing</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>teamID</key>
              <string></string>
              <key>provisioningProfiles</key>
              <dict/>
            </dict>
            </plist>
            EOF

      - name: Générer l’IPA avec Xcode
        run: |
          cd project/ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath build/Runner.xcarchive \
            CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" DEVELOPMENT_TEAM="" PROVISIONING_PROFILE_SPECIFIER=""

          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportPath build/ios \
            -exportOptionsPlist ./ExportOptions.plist \
            CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" DEVELOPMENT_TEAM="" PROVISIONING_PROFILE_SPECIFIER=""

      - name: Sauvegarder l’IPA en artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: project/build/ios/ipa/*.ipa
          compression-level: 0